// export { default as File } from "./3_CreatingFirstClass";
// export { default as File } from "./5_ConstructorFun";
// export { default as File } from "./6_PrivtePublic";
// export { default as File } from "./7_ShortHandInitialization";
// export { default as File } from "./8_ReadOnly";
// export { default as File } from "./9_Inheritance";
// export { default as File } from "./10_OverridingProperties";
// export { default as File } from "./11_Getters&Setters";
// export { default as File } from "./12_StaticMethods";
// export { default as File } from "./13_AbstractClasses";
// export { default as File } from "./14_Singletons&PrivateConstructors";
// export { default as File } from "./16_FitstInterface";
// export { default as File } from "./17_UsingInterface";
// export { default as File } from "./20_ExtendingInterface";
export { default as File } from "./21_InterfaceAsFunctionType";
